cumbia-image plugin: QuImgZoomer Class Reference
QuImgZoomer Class Reference
#include <quimgzoomer.h>
Public Member Functions
QuImgZoomer (bool enable, QuImageBasePrivate *img_d)
virtual ~QuImgZoomer ()
void setLevel (float n)
float level () const
void setEnabled (bool en)
bool enabled () const
QRect unzoom ()
QRect zoom (const QRect &r)
zoom the rect r, which is in image coordinates!
QList< QRect > zoomStack () const
Constructor & Destructor Documentation
QuImgZoomer()
QuImgZoomer::QuImgZoomer (bool enable, QuImageBasePrivate * img_d)
References QuImgZoomerPrivate::enabled, QuImgZoomerPrivate::img_d, and QuImgZoomerPrivate::level.
~QuImgZoomer()
QuImgZoomer::~QuImgZoomer () virtual
Member Function Documentation
enabled()
bool QuImgZoomer::enabled () const
References QuImgZoomerPrivate::enabled.
Referenced by QuImgMouseTracker::mouseRelease(), and QuImageBase::zoomEnabled().
level()
float QuImgZoomer::level () const
References QuImgZoomerPrivate::level.
Referenced by QuImgPainter::paint(), and QuImageBase::zoomLevel().
setEnabled()
void QuImgZoomer::setEnabled (bool en)
References QuImgZoomerPrivate::enabled.
Referenced by QuImageBase::setScaleContents(), and QuImageBase::setZoomEnabled().
setLevel()
void QuImgZoomer::setLevel (float n)
References QuImgZoomerPrivate::level.
Referenced by QuImageBase::setZoomLevel().
unzoom()
QRect QuImgZoomer::unzoom ()
References QuImgZoomerPrivate::enabled, and QuImgZoomerPrivate::zoom_stack.
Referenced by QuImgMouseTracker::mouseRelease().
zoom()
QRect QuImgZoomer::zoom (const QRect & r)
Parameters
r the zoom rectangle in image coordinates
References QuImgZoomerPrivate::enabled, and QuImgZoomerPrivate::zoom_stack.
Referenced by QuImgMouseTracker::mouseRelease().
zoomStack()
QList< QRect > QuImgZoomer::zoomStack () const
References QuImgZoomerPrivate::zoom_stack.
Referenced by QuImgMouseTracker::mouseRelease().
The documentation for this class was generated from the following files:
quimgzoomer.h
quimgzoomer.cpp