cumbia-image plugin: QuImgConfDialog Class Reference
QuImgConfDialog Class Reference
#include <quimgconfdialog.h>
Public Slots
void applyClicked ()
Public Member Functions
QuImgConfDialog (QuImgConfDialogListener *li, QWidget *parent)
~QuImgConfDialog ()
QString getColorTableName () const
Constructor & Destructor Documentation
QuImgConfDialog()
QuImgConfDialog::QuImgConfDialog (QuImgConfDialogListener * li, QWidget * parent) explicit
References applyClicked().
~QuImgConfDialog()
QuImgConfDialog::~QuImgConfDialog ()
Member Function Documentation
applyClicked
void QuImgConfDialog::applyClicked () slot
References getColorTableName(), and QuImgConfDialogListener::onApply().
Referenced by QuImgConfDialog().
getColorTableName()
QString QuImgConfDialog::getColorTableName () const
Referenced by applyClicked().
The documentation for this class was generated from the following files:
quimgconfdialog.h
quimgconfdialog.cpp