cumbia-image plugin: QuImgMouseTracker Class Reference
QuImgMouseTracker Class Reference
#include <quimgmousetracker.h>
Public Member Functions
QuImgMouseTracker (QuImageBasePrivate *_img_d, QuImgZoomer *z)
void mouseMove (QMouseEvent *e)
void mousePress (QMouseEvent *e)
void mouseRelease (QMouseEvent *e)
void wheelEvent (QWheelEvent *event)
void setMouseEventInterface (QuImageMouseEventIf *i)
Public Attributes
QPoint mP1
QPoint mP2
bool left_button
Constructor & Destructor Documentation
QuImgMouseTracker()
QuImgMouseTracker::QuImgMouseTracker (QuImageBasePrivate * _img_d, QuImgZoomer * z)
Member Function Documentation
mouseMove()
void QuImgMouseTracker::mouseMove (QMouseEvent * e)
References QuImageMouseEventIf::imageMouseMoveEvent(), mP1, mP2, and QuImageBasePrivate::widget.
Referenced by QuImageBase::mouseMove().
mousePress()
void QuImgMouseTracker::mousePress (QMouseEvent * e)
References QuImageMouseEventIf::imageMousePressEvent(), left_button, mP1, and QuImageBasePrivate::widget.
Referenced by QuImageBase::mousePress().
mouseRelease()
void QuImgMouseTracker::mouseRelease (QMouseEvent * e)
References QuImgZoomer::enabled(), QuImageMouseEventIf::imageMouseReleaseEvent(), QuImageBasePrivate::listener, QuImageBasePrivate::mapToImg(), mP1, mP2, QuImageBaseListener::onZoom(), QuImgZoomer::unzoom(), QuImageBasePrivate::widget, QuImgZoomer::zoom(), and QuImgZoomer::zoomStack().
Referenced by QuImageBase::mouseRelease().
setMouseEventInterface()
void QuImgMouseTracker::setMouseEventInterface (QuImageMouseEventIf * i)
Referenced by QuImageBase::setImageMouseEventInterface().
wheelEvent()
void QuImgMouseTracker::wheelEvent (QWheelEvent * event)
References QuImageMouseEventIf::imageMouseWheelEvent().
Referenced by QuImageBase::wheelEvent().
Member Data Documentation
left_button
bool QuImgMouseTracker::left_button
Referenced by mousePress(), and QuImgPainter::paint().
mP1
QPoint QuImgMouseTracker::mP1
Referenced by mouseMove(), mousePress(), mouseRelease(), and QuImgPainter::paint().
mP2
QPoint QuImgMouseTracker::mP2
Referenced by mouseMove(), mouseRelease(), and QuImgPainter::paint().
The documentation for this class was generated from the following files:
quimgmousetracker.h
quimgmousetracker.cpp