cumbia-image plugin: QuImgScrollArea Class Reference
QuImgScrollArea Class Reference
#include <quimgscrollarea.h>
Public Slots
void onZoomRectChanged (const QRect &from, const QRect &to)
void setScaleContents (bool scale)
Public Member Functions
QuImgScrollArea (QWidget *parent)
~QuImgScrollArea ()
bool scrollEnabled () const
QScrollArea * scrollArea ()
void setImage (QuImageBaseI *ii)
Public Member Functions inherited from QuImgScrollAreaI
virtual ~QuImgScrollAreaI ()
virtual void setScaleContents (bool scale)=0
Constructor & Destructor Documentation
QuImgScrollArea()
QuImgScrollArea::QuImgScrollArea (QWidget * parent)
References QuImgScrollAreaPrivate::ii.
~QuImgScrollArea()
QuImgScrollArea::~QuImgScrollArea ()
Member Function Documentation
onZoomRectChanged
void QuImgScrollArea::onZoomRectChanged (const QRect & from, const QRect & to) slot
References QuImgScrollAreaPrivate::ii, and QuImageBaseI::mapFromImg().
Referenced by setImage().
scrollArea()
QScrollArea * QuImgScrollArea::scrollArea () virtual
Implements QuImgScrollAreaI.
scrollEnabled()
bool QuImgScrollArea::scrollEnabled () const
setImage()
void QuImgScrollArea::setImage (QuImageBaseI * ii) virtual
Implements QuImgScrollAreaI.
References QuImageBaseI::asWidget(), QuImgScrollAreaPrivate::ii, and onZoomRectChanged().
setScaleContents
void QuImgScrollArea::setScaleContents (bool scale) slot
References QuImgScrollAreaPrivate::ii, and QuImageBaseI::setScaleContents().
The documentation for this class was generated from the following files:
quimgscrollarea.h
quimgscrollarea.cpp