cumbia-image plugin: QuImageBase Class Reference
QuImageBase Class Reference
#include <quimagebase.h>
Public Member Functions
QuImageBase (QWidget *widget, bool isOpenGL, CumbiaPool *cu_p, const CuControlsFactoryPool &fpoo)
virtual ~QuImageBase ()
QWidget * asWidget () const
QImage & image () const
void setImage (const QImage &img)
virtual void setImage (const CuMatrix< double > &data)
virtual void setImage (const CuMatrix< unsigned short > &data)
virtual void setImage (const CuMatrix< unsigned char > &data)
void setImageMouseEventInterface (ImageMouseEventInterface *ifa)
void setScaleContents (bool fit)
bool scaleContents () const
bool error () const
void setError (bool error)
void setErrorMessage (const QString &msg)
void setErrorImage (const QImage &i)
QImage errorImage () const
void setColorTable (const QVector< QRgb > &rgb)
QVector< QRgb > & colorTable () const
void setZoomLevel (float f)
void setZoomEnabled (bool en)
bool zoomEnabled () const
float zoomLevel () const
bool isOpenGL () const
void setImageMouseEventInterface (QuImageMouseEventIf *ifa)
void mouseMove (QMouseEvent *e)
void mousePress (QMouseEvent *e)
void mouseRelease (QMouseEvent *e)
void wheelEvent (QWheelEvent *event)
void paint (QPaintEvent *e, QWidget *widget)
void execConfigDialog ()
QString source () const
void setSource (const QString &src)
void unsetSource ()
QPoint mapToImg (const QPoint &p) const
maps point p in widget coordinates to the corresponding pixel in the image
QRect mapToImg (const QRect &r) const
QPoint mapFromImg (const QPoint &p) const
QRect mapFromImg (const QRect &p) const
void setImageBaseListener (QuImageBaseListener *li)
void setPainterDirty (bool di)
void onApply (const QMap< QString, QVariant > &conf)
Public Member Functions inherited from QuImageBaseI
virtual ~QuImageBaseI ()
Constructor & Destructor Documentation
QuImageBase()
QuImageBase::QuImageBase (QWidget * widget, bool isOpenGL, CumbiaPool * cu_p, const CuControlsFactoryPool & fpoo)
References QuImageBasePrivate::colorTable, QuImageBasePrivate::errorImage, QuImageBasePrivate::image, QuImageBasePrivate::isOpenGL, isOpenGL(), QuImageBasePrivate::listener, QuImageBasePrivate::noise, and QuImageBasePrivate::widget.
~QuImageBase()
QuImageBase::~QuImageBase () virtual
Member Function Documentation
asWidget()
QWidget * QuImageBase::asWidget () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::widget.
Referenced by QuImageGLWidget::asWidget(), and QuImageWidget::asWidget().
colorTable()
QVector< QRgb > & QuImageBase::colorTable () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::colorTable.
Referenced by QuImageGLWidget::colorTable(), and QuImageWidget::colorTable().
error()
bool QuImageBase::error () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::error.
Referenced by QuImageGLWidget::error(), QuImageWidget::error(), and setError().
errorImage()
QImage QuImageBase::errorImage () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::errorImage.
Referenced by QuImageGLWidget::errorImage(), and QuImageWidget::errorImage().
execConfigDialog()
void QuImageBase::execConfigDialog ()
References QuImageBasePrivate::widget.
Referenced by QuImageWidget::execConfigDialog().
image()
QImage & QuImageBase::image () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::image.
Referenced by QuImageGLWidget::image(), QuImageWidget::image(), and QuImageWidget::setImage().
isOpenGL()
bool QuImageBase::isOpenGL () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::isOpenGL.
Referenced by QuImageBase().
mapFromImg() [1/2]
QPoint QuImageBase::mapFromImg (const QPoint & p) const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::mapFromImg().
Referenced by QuImageGLWidget::mapFromImg(), and QuImageWidget::mapFromImg().
mapFromImg() [2/2]
QRect QuImageBase::mapFromImg (const QRect & p) const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::mapFromImg().
mapToImg() [1/2]
QPoint QuImageBase::mapToImg (const QPoint & p) const virtual
Parameters
p a point on the widget
Returns
p mapped to image coords
Implements QuImageBaseI.
References QuImageBasePrivate::mapToImg().
Referenced by QuImageGLWidget::mapToImg(), and QuImageWidget::mapToImg().
mapToImg() [2/2]
QRect QuImageBase::mapToImg (const QRect & r) const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::mapToImg().
mouseMove()
void QuImageBase::mouseMove (QMouseEvent * e)
References QuImageBasePrivate::mouse_t, QuImgMouseTracker::mouseMove(), and QuImageBasePrivate::widget.
Referenced by QuImageGLWidget::mouseMoveEvent(), and QuImageWidget::mouseMoveEvent().
mousePress()
void QuImageBase::mousePress (QMouseEvent * e)
References QuImageBasePrivate::mouse_t, QuImgMouseTracker::mousePress(), and QuImageBasePrivate::widget.
Referenced by QuImageGLWidget::mousePressEvent(), and QuImageWidget::mousePressEvent().
mouseRelease()
void QuImageBase::mouseRelease (QMouseEvent * e)
References QuImageBasePrivate::mouse_t, QuImgMouseTracker::mouseRelease(), and QuImageBasePrivate::widget.
Referenced by QuImageGLWidget::mouseReleaseEvent(), and QuImageWidget::mouseReleaseEvent().
onApply()
void QuImageBase::onApply (const QMap< QString, QVariant > & conf) virtual
Implements QuImgConfDialogListener.
References QuImageBasePrivate::image, and QuImageBasePrivate::widget.
paint()
void QuImageBase::paint (QPaintEvent * e, QWidget * widget)
References QuImgPainter::paint(), and QuImageBasePrivate::painter.
Referenced by QuImageGLWidget::paintEvent(), and QuImageWidget::paintEvent().
scaleContents()
bool QuImageBase::scaleContents () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::scale_contents.
Referenced by QuImageWidget::minimumSizeHint(), QuImageGLWidget::scaleContents(), QuImageWidget::scaleContents(), and QuImageWidget::setImage().
setColorTable()
void QuImageBase::setColorTable (const QVector< QRgb > & rgb) virtual
Implements QuImageBaseI.
References QuImageBasePrivate::colorTable, and QuImageBasePrivate::image.
Referenced by QuImageGLWidget::setColorTable(), and QuImageWidget::setColorTable().
setError()
void QuImageBase::setError (bool error) virtual
Implements QuImageBaseI.
References QuImageBasePrivate::error, and error().
Referenced by QuImageGLWidget::setError(), and QuImageWidget::setError().
setErrorImage()
void QuImageBase::setErrorImage (const QImage & i) virtual
Implements QuImageBaseI.
References QuImageBasePrivate::errorImage.
Referenced by QuImageGLWidget::setErrorImage(), and QuImageWidget::setErrorImage().
setErrorMessage()
void QuImageBase::setErrorMessage (const QString & msg) virtual
Implements QuImageBaseI.
References QuImageBasePrivate::errorMessage.
Referenced by QuImageGLWidget::setErrorMessage(), and QuImageWidget::setErrorMessage().
setImage() [1/4]
void QuImageBase::setImage (const CuMatrix< double > & data) virtual
Implements QuImageBaseI.
setImage() [2/4]
void QuImageBase::setImage (const CuMatrix< unsigned char > & data) virtual
Implements QuImageBaseI.
setImage() [3/4]
void QuImageBase::setImage (const CuMatrix< unsigned short > & data) virtual
Implements QuImageBaseI.
setImage() [4/4]
void QuImageBase::setImage (const QImage & img) virtual
Implements QuImageBaseI.
References QuImgPainter::dirty, QuImageBasePrivate::image, and QuImageBasePrivate::painter.
Referenced by QuImageWidget::onNewData(), QuImageGLWidget::setImage(), and QuImageWidget::setImage().
setImageBaseListener()
void QuImageBase::setImageBaseListener (QuImageBaseListener * li)
References QuImageBasePrivate::listener.
Referenced by QuImageWidget::QuImageWidget().
setImageMouseEventInterface() [1/2]
void QuImageBase::setImageMouseEventInterface (ImageMouseEventInterface * ifa)
Referenced by QuImageGLWidget::setImageMouseEventInterface(), and QuImageWidget::setImageMouseEventInterface().
setImageMouseEventInterface() [2/2]
void QuImageBase::setImageMouseEventInterface (QuImageMouseEventIf * ifa) virtual
Implements QuImageBaseI.
References QuImageBasePrivate::mouse_t, and QuImgMouseTracker::setMouseEventInterface().
setPainterDirty()
void QuImageBase::setPainterDirty (bool di)
References QuImgPainter::dirty, and QuImageBasePrivate::painter.
Referenced by QuImageWidget::resizeEvent().
setScaleContents()
void QuImageBase::setScaleContents (bool fit) virtual
Implements QuImageBaseI.
References QuImgPainter::dirty, QuImageBasePrivate::painter, QuImageBasePrivate::scale_contents, QuImgZoomer::setEnabled(), QuImageBasePrivate::widget, and QuImageBasePrivate::zoomer.
Referenced by QuImageWidget::setScaleContents(), and QuImageGLWidget::setScaleContents().
setSource()
void QuImageBase::setSource (const QString & src) virtual
Implements QuImageBaseI.
References QuImageBasePrivate::cu_pool, QuImageBasePrivate::fpool, and QuImageBasePrivate::widget.
Referenced by QuImageGLWidget::setSource(), and QuImageWidget::setSource().
setZoomEnabled()
void QuImageBase::setZoomEnabled (bool en) virtual
Implements QuImageBaseI.
References QuImgPainter::dirty, QuImageBasePrivate::painter, QuImgZoomer::setEnabled(), QuImageBasePrivate::widget, and QuImageBasePrivate::zoomer.
Referenced by QuImageGLWidget::setZoomEnabled(), and QuImageWidget::setZoomEnabled().
setZoomLevel()
void QuImageBase::setZoomLevel (float f) virtual
Implements QuImageBaseI.
References QuImgPainter::dirty, QuImageBasePrivate::painter, QuImgZoomer::setLevel(), QuImageBasePrivate::widget, and QuImageBasePrivate::zoomer.
Referenced by QuImageGLWidget::setZoomLevel(), and QuImageWidget::setZoomLevel().
source()
QString QuImageBase::source () const virtual
Implements QuImageBaseI.
References QuImageBasePrivate::widget.
Referenced by QuImageGLWidget::source(), and QuImageWidget::source().
unsetSource()
void QuImageBase::unsetSource () virtual
Implements QuImageBaseI.
References QuImageBasePrivate::widget.
Referenced by QuImageGLWidget::unsetSource(), and QuImageWidget::unsetSource().
wheelEvent()
void QuImageBase::wheelEvent (QWheelEvent * event)
References QuImageBasePrivate::mouse_t, QuImgMouseTracker::wheelEvent(), and QuImageBasePrivate::widget.
zoomEnabled()
bool QuImageBase::zoomEnabled () const virtual
Implements QuImageBaseI.
References QuImgZoomer::enabled(), and QuImageBasePrivate::zoomer.
Referenced by QuImageGLWidget::zoomEnabled(), and QuImageWidget::zoomEnabled().
zoomLevel()
float QuImageBase::zoomLevel () const virtual
Implements QuImageBaseI.
References QuImgZoomer::level(), and QuImageBasePrivate::zoomer.
Referenced by QuImageWidget::setImage(), QuImageGLWidget::zoomLevel(), and QuImageWidget::zoomLevel().
The documentation for this class was generated from the following files:
quimagebase.h
quimagebase.cpp