cumbia-image plugin: QuImageWidget Class Reference
QuImageWidget Class Reference
QWidget implementing QuImageBaseI.
#include <quimagewidget.h>
Public Slots
void setImage (const QImage &image)
slot version of QuImageBaseI::setImage(const QImage& img)
void setErrorImage (const QImage &img)
slot version of QuImageBaseI::setErrorImage
void setErrorMessage (const QString &msg)
void setError (bool error)
bool error () const
void setOk (bool ok)
clear the error flag
void execConfigDialog ()
void setScaleContents (bool fit)
QWidget * asWidget () const
void onNewData (const CuData &da)
slot executed to update the image with the new data
Signals
void zoomRectChanged (const QRect &from_z, const QRect &to_z)
zoomRectChanged is emitted when the zoom rect changes from from_z to to_z, in image coordinates
Public Member Functions
QuImageWidget (QWidget *parent, CumbiaPool *cu_p, const CuControlsFactoryPool &fpoo)
bool scaleContents () const
scaleContents returns the value of the scaleContents property
QImage errorImage () const
errorImage returns the image displayed in case of error condition
void setImage (const CuMatrix< double > &image)
setImage double data type version
void setImage (const CuMatrix< unsigned short > &image)
setImage unsigned short data type version
void setImage (const CuMatrix< unsigned char > &image)
setImage unsigned char data type version
QImage & image () const
image returns the currently displayed image as QImage
void setColorTable (const QVector< QRgb > &rgb)
apply the given color table to the image
QVector< QRgb > & colorTable () const
colorTable returns the color table currently in use
void setImageMouseEventInterface (QuImageMouseEventIf *ifa)
install a custom mouse event handler
bool isOpenGL () const
isOpenGL shall return true if the implementation of QuImageBaseI is a QOpenGLWidget
bool mouseZoomEnabled () const
returns true if the mouse zoom is enabled
void setZoomLevel (float n)
programmatically set a zoom level
void setMouseZoomEnabled (bool en)
enable or disable the zoom
float zoomLevel () const
returns the current zoom level
QString source () const
returns the source of the connection
void setSource (const QString &src)
set a source for the cumbia connection
void unsetSource ()
stop reading from the engine source to update the image
virtual QPoint mapToImg (const QPoint &p) const
map the point p from widget to image coordinates
virtual QRect mapToImg (const QRect &r) const
map the QRect r from widget to image coordinates
virtual QPoint mapFromImg (const QPoint &p) const
map the point p from image to widget coordinates
virtual QRect mapFromImg (const QRect &r) const
map the rect r from image to widget coordinates
void onZoom (const QRect &from_z, const QRect &to_z)
Public Member Functions inherited from QuImageBaseI
virtual void setImage (const QImage &img)=0
setImage from QImage
virtual void setScaleContents (bool scale)=0
setScaleContents: if true the image scales with the widget's geometry
virtual bool error () const =0
error returns the error condition
virtual void setErrorImage (const QImage &i)=0
setErrorImage set the image to be used in case of error
virtual void setError (bool error)=0
setError manually set (or clear) an error condition
virtual void setErrorMessage (const QString &msg)=0
set a specific message to display in case of error condition
virtual QWidget * asWidget () const =0
return this object as QWidget, to exploit Qt properties and signal/slots
Protected Member Functions
QSize minimumSizeHint () const
QSize sizeHint () const
void paintEvent (QPaintEvent *)
void mousePressEvent (QMouseEvent *ev)
void mouseMoveEvent (QMouseEvent *ev)
void mouseReleaseEvent (QMouseEvent *ev)
void wheelEvent (QWheelEvent *we)
void contextMenuEvent (QContextMenuEvent *e)
execute an image configuration menu
void resizeEvent (QResizeEvent *re)
Properties
bool scaleContents
QImage errorImage
Detailed Description
This object is controlled through QuImageBaseI interface only. QuImageBaseI::asWidget returns this as QWidget so that properties, signals and slots can be used if more convenient.
Member Function Documentation
colorTable()
QVector< QRgb > & QuImageWidget::colorTable () const virtual
Returns
QVector<QRgb>&
Implements QuImageBaseI.
errorImage()
QImage QuImageWidget::errorImage () const virtual
Returns
QImage used in case of error
Implements QuImageBaseI.
image()
QImage & QuImageWidget::image () const virtual
Returns
a reference to the current image in use
Implements QuImageBaseI.
Referenced by setImage().
isOpenGL()
bool QuImageWidget::isOpenGL () const virtual
Returns
true if the implementation of QuImageBaseI is a QOpenGLWidget
false if the implementation of QuImageBaseI is a QWidget
Implements QuImageBaseI.
mapFromImg() [1/2]
QPoint QuImageWidget::mapFromImg (const QPoint & p) const virtual
Parameters
p a QPoint in image coordinates
Returns
a QPoint in the widget coordinates
Implements QuImageBaseI.
mapFromImg() [2/2]
QRect QuImageWidget::mapFromImg (const QRect & r) const virtual
Parameters
r a QRect in image coordinates
Returns
a QRect in the widget coordinates
Implements QuImageBaseI.
mapToImg() [1/2]
QPoint QuImageWidget::mapToImg (const QPoint & p) const virtual
Parameters
p a QPoint in widget coordinates
Returns
a QPoint in the image coordinates
Implements QuImageBaseI.
mapToImg() [2/2]
QRect QuImageWidget::mapToImg (const QRect & r) const virtual
Parameters
r a QRect in widget coordinates
Returns
a QRect in the image coordinates
Implements QuImageBaseI.
mouseZoomEnabled()
bool QuImageWidget::mouseZoomEnabled () const virtual
Returns
true the zoom is enabled
Note
this function may return true while the zoom still is unavailable because scaleContents is enabled.
calling setZoomLevel with a value different from 100 disables the mouse zoom and clears the zoom stack (the zoom history)
Implements QuImageBaseI.
onNewData
void QuImageWidget::onNewData (const CuData & da) slot
Parameters
da CuData
The supported types are those declared in the setImage methods of QuImageBaseI
Supported data types:
double
unsigned char
unsigned short
int (converted to unsigned char)
scaleContents()
bool QuImageWidget::scaleContents () const virtual
See also
setScaleContents
Implements QuImageBaseI.
setColorTable()
void QuImageWidget::setColorTable (const QVector< QRgb > & rgb) virtual
Parameters
rgb a QVector of QRgb values
Implements QuImageBaseI.
setErrorImage
void QuImageWidget::setErrorImage (const QImage & img) slot
Parameters
img a QImage to be displayed in case of error
setImage() [1/4]
void QuImageWidget::setImage (const CuMatrix< double > & image) virtual
Parameters
image CuMatrix of double
Implements QuImageBaseI.
References image().
setImage() [2/4]
void QuImageWidget::setImage (const CuMatrix< unsigned char > & image) virtual
Parameters
image CuMatrix of unsigned char
Implements QuImageBaseI.
References image().
setImage() [3/4]
void QuImageWidget::setImage (const CuMatrix< unsigned short > & image) virtual
Parameters
image CuMatrix of unsigned short
Implements QuImageBaseI.
References image().
setImage [4/4]
void QuImageWidget::setImage (const QImage & img) slot
Parameters
img a QImage
setImageMouseEventInterface()
void QuImageWidget::setImageMouseEventInterface (QuImageMouseEventIf * ifa) virtual
Parameters
ifa an implementation of QuImageMouseEventIf.
Note
Mouse events are sent to the interface without local processing
Implements QuImageBaseI.
setMouseZoomEnabled()
void QuImageWidget::setMouseZoomEnabled (bool en) virtual
Parameters
en true zoom enabled.
Note
scale contents property must be false
calling this function with a true value resets zoomLevel to 100. On the other hand, calling setZoomLevel with a value different from 100 disables mouse zoom and clears the zoom stack (the zoom history). To enable mouse zoom again after setZoomLevel, call setMouseZoomEnabled again.
Implements QuImageBaseI.
setOk
void QuImageWidget::setOk (bool ok) slot
Parameters
equivalent to setError(!ok)
setSource()
void QuImageWidget::setSource (const QString & src) virtual
Parameters
src the source name, depending on the control system in use.
See cumbia documentation for details on modules and supported engines.
Implements QuImageBaseI.
setZoomLevel()
void QuImageWidget::setZoomLevel (float l) virtual
Parameters
l the zoom level from 0 to 100 (percent)
Note
Usually zooming is accomplished mouse-selecting a rectangular region on the image
scale contents must be false in order for zoom to operate
calling this function with l different from 100 disables mouse zoom. To enable mouse zoom again after setZoomLevel, call setMouseZoomEnabled again.
Implements QuImageBaseI.
source()
QString QuImageWidget::source () const virtual
Returns
a QString
Refer to cumbia documentation for supported engines and source syntax (which depends on the engine)
See also
setSource
unsetSource
Implements QuImageBaseI.
unsetSource()
void QuImageWidget::unsetSource () virtual
Removes the connection to a previously specified source
Implements QuImageBaseI.
zoomLevel()
float QuImageWidget::zoomLevel () const virtual
Returns
the zoom level, from 0 to 100
See also
setZoomLevel
Implements QuImageBaseI.
zoomRectChanged
void QuImageWidget::zoomRectChanged (const QRect & from_z, const QRect & to_z) signal
Parameters
from_z previous zoom rect, in image coordinates
to_z current zoom rect, in image cooridinates
The documentation for this class was generated from the following files:
quimagewidget.h
quimagewidget.cpp