cumbia-image plugin: QuImagePluginInterface Class Reference
QuImagePluginInterface Class Reference abstract
#include <quimageplugininterface.h>
Public Member Functions
virtual ~QuImagePluginInterface ()
virtual void init (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)=0
Initialise the image reader with mixed engine mode (CumbiaPool + CuControlsFactoryPool).
virtual const QObject * get_qobject () const =0
Get a pointer to QuImagePlugin, that implements QuImagePluginInterface and is a QObject.
virtual QuImageBaseI * new_image (QWidget *parent, bool opengl=false) const =0
get_image returns a new QuImageI object with the given parent
virtual QuImgScrollAreaI * new_scroll_area (QWidget *parent) const =0
new_scroll_area returns a new instance of QuImgScrollAreaI
virtual void layout (QuImageBaseI *ii, QWidget *container)=0
convenience method to layout an image into a container (that has no layout yet)
virtual void layout (QuImgScrollAreaI *scroll_a, QWidget *container)=0
the same method as the above layout pertaining to a scroll area instead of an image
Static Public Member Functions
static QuImagePluginInterface * get_instance (CumbiaPool *cu_poo, const CuControlsFactoryPool &fpoo, QObject **plugin_qob)
QuImagePluginInterface::get_instance returns a new instance of the plugin.
static QString file_name ()
file_name returns this plugin's file name
Constructor & Destructor Documentation
~QuImagePluginInterface()
virtual QuImagePluginInterface::~QuImagePluginInterface () inline virtual
Member Function Documentation
file_name()
static QString QuImagePluginInterface::file_name () inline static
Returns
the name of the plugin: libcumbia-image-plugin.so.
Referenced by get_instance().
get_instance()
static QuImagePluginInterface* QuImagePluginInterface::get_instance (CumbiaPool * cu_poo, const CuControlsFactoryPool & fpoo, QObject ** plugin_qob) inline static
Parameters
cu_poo pointer to a previously allocated CumbiaPool
fpoo const reference to CuControlsFactoryPool
plugin_qob a pointer to a QObject, will contain this plugin as QObject (for signals and slots)
Returns
an instance of the plugin or nullptr in case of failure.
Note
Repeated calls will return the same plugin instance (by Qt plugin nature) Use QuImagePluginInterface::new_image to get new instances
References file_name(), and init().
get_qobject()
virtual const QObject* QuImagePluginInterface::get_qobject () const pure virtual
Obtaining a reference to this plugin as QObject allows to use Qt properties and signal/slots.
Returns
This plugin as QObject.
Implemented in CuImagePlugin.
init()
virtual void QuImagePluginInterface::init (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool) pure virtual
This call is necessary if you want to setSource on the image later and display an image from cumbia.
Parameters
cumbia_pool a reference to the CumbiaPool engine chooser
fpool the CuControlsFactoryPool factory chooser
Implemented in CuImagePlugin.
Referenced by get_instance().
layout() [1/2]
virtual void QuImagePluginInterface::layout (QuImageBaseI * ii, QWidget * container) pure virtual
Parameters
ii an image as QuImageBaseI
container the widget that will contain the image (QHBoxLayout will be used)
If you are embedding an image into a QuImgScrollAreaI, consider using the convenience method below
See also
layout(QuImgScrollAreaI scroll_a, QWidget container)
Implemented in CuImagePlugin.
layout() [2/2]
virtual void QuImagePluginInterface::layout (QuImgScrollAreaI * scroll_a, QWidget * container) pure virtual
See also
layout(QuImageBaseI ii, QWidget container)
Implemented in CuImagePlugin.
new_image()
virtual QuImageBaseI* QuImagePluginInterface::new_image (QWidget * parent, bool opengl = false) const pure virtual
Returns
a new instance of an object implementing QuImageI interface
Implementations
QuImageBaseI is implemented by QuImageWidget, QuImageGLWidget and QuImageBase. The latter is a class used by QuImageWidget and QuImageGLWidget to implement common functionality. It shall not be used by the clients of this plugin. QuImageWidget and QuImageGLWidget are the plugin implementations and cannot be used by the clients of the library with the exception of signal / slot connections. Clients shall use QuImageBaseI interface to control QuImageWidget and QuImageGLWidget and, where convenient, QuImageWidget and QuImageGLWidget signals and slots.
See also
new_scroll_area
QuImageWidget
QuImageGLWidget
Implemented in CuImagePlugin.
new_scroll_area()
virtual QuImgScrollAreaI* QuImagePluginInterface::new_scroll_area (QWidget * parent) const pure virtual
Parameters
parent the parent QWidget
Returns
a QScrollArea that implements QuImgScrollAreaI and handles changes in the image geometry.
Example
QGridLayout *lo = new QGridLayout(this); // layout
QuImgScrollAreaI *sa = plugin_i->new_scroll_area(this);
QuImageBaseI *ii = plugin_i->new_image(this);
ii->setImage(QImage(":/seoyeji.png"));
sa->setImage(d->ii);
lo->addWidget(sa->scrollArea(), 0, 0, 6, 6);
See also
QuImgScrollAreaI
QuImgScrollAreaI::scrollArea
Implemented in CuImagePlugin.
The documentation for this class was generated from the following file:
quimageplugininterface.h