cumbia-magic plugin: CuImagePluginInterface Class Reference
CuImagePluginInterface Class Reference abstract
#include <quimageplugininterface.h>
Public Member Functions
virtual ~CuImagePluginInterface ()
virtual void init (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)=0
Initialise the multi reader with mixed engine mode and the read mode.
virtual const QObject * get_qobject () const =0
To provide the necessary signals aforementioned, the implementation must derive from Qt QObject. This method returns the subclass as a QObject, so that the client can connect to the multi reader signals.
virtual QuImageBaseI * new_image (QWidget *parent, bool opengl=false) const =0
get_image returns a new QuImageI object with parent the given QObject
Static Public Member Functions
static CuImagePluginInterface * get_instance (CumbiaPool *cu_poo, const CuControlsFactoryPool &fpoo, QObject **plugin_qob)
CuImagePluginInterface::get_instance returns a new instance of the plugin.
static QString file_name ()
Constructor & Destructor Documentation
~CuImagePluginInterface()
virtual CuImagePluginInterface::~CuImagePluginInterface () inline virtual
Member Function Documentation
file_name()
static QString CuImagePluginInterface::file_name () inline static
Referenced by get_instance().
get_instance()
static CuImagePluginInterface* CuImagePluginInterface::get_instance (CumbiaPool * cu_poo, const CuControlsFactoryPool & fpoo, QObject ** plugin_qob) inline static
Parameters
cu_poo pointer to a previously allocated CumbiaPool
fpoo const reference to CuControlsFactoryPool
plugin_qob a pointer to a QObject, will contain this plugin as QObject (for signals and slots)
Returns
an instance of the plugin or nullptr in case of failure.
Note
Repeated calls will return the same plugin instance (by Qt plugin nature) Use CuImagePluginInterface::new_image to get new instances
References file_name(), and init().
get_qobject()
virtual const QObject* CuImagePluginInterface::get_qobject () const pure virtual
Returns
The object implementing QuImageI as a QObject.
Implemented in CuImagePlugin.
init()
virtual void CuImagePluginInterface::init (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool) pure virtual
Parameters
cumbia a reference to the CumbiaPool engine chooser
r_fac the CuControlsFactoryPool factory chooser
Implemented in CuImagePlugin.
Referenced by get_instance().
new_image()
virtual QuImageBaseI* CuImagePluginInterface::new_image (QWidget * parent, bool opengl = false) const pure virtual
Returns
a new instance of an object implementing QuImageI interface
See also
new_image_base
Implemented in CuImagePlugin.
The documentation for this class was generated from the following file:
quimageplugininterface.h