cumbia-image plugin: QuImageBaseI Class Reference
QuImageBaseI Class Reference abstract
Interface to the cumbia widget to display images.
#include <quimageplugininterface.h>
Public Member Functions
virtual ~QuImageBaseI ()
virtual void setImage (const CuMatrix< double > &image)=0
virtual void setImage (const CuMatrix< unsigned short > &image)=0
virtual void setImage (const CuMatrix< unsigned char > &image)=0
virtual void setImage (const QImage &img)=0
virtual QImage & image () const =0
virtual void setScaleContents (bool scale)=0
virtual bool scaleContents () const =0
virtual bool error () const =0
virtual void setErrorImage (const QImage &i)=0
virtual QImage errorImage () const =0
virtual void setError (bool error)=0
virtual void setErrorMessage (const QString &msg)=0
virtual void setColorTable (const QVector< QRgb > &rgb)=0
virtual QVector< QRgb > & colorTable () const =0
virtual void setImageMouseEventInterface (QuImageMouseEventIf *ifa)=0
virtual bool isOpenGL () const =0
virtual QPoint mapToImg (const QPoint &p) const =0
virtual QRect mapToImg (const QRect &p) const =0
virtual QPoint mapFromImg (const QPoint &p) const =0
virtual QRect mapFromImg (const QRect &p) const =0
virtual bool zoomEnabled () const =0
virtual void setZoomEnabled (bool en)=0
virtual float zoomLevel () const =0
virtual void setZoomLevel (float l)=0
virtual QWidget * asWidget () const =0
virtual QString source () const =0
virtual void setSource (const QString &src)=0
virtual void unsetSource ()=0
Detailed Description
QuImageBaseI defines an interface for clients of the plugin to control the behaviour of the cumbia image display widget implementations, namely QuImageWidget and QuImageGLWidget. These two implement QWidget and they can be accessed as QWidget*s through the *asWidget method. This allows the clients to use Qt properties and signal/slot connections. For the rest, QuImageWidget and QuImageGLWidget shall only be controlled through the QuImageBaseI interface.
There are some setImage flavors to set an image on the widget. An image can be set manually as a QImage or using cumbia CuMatrix image container. For the basic automatic usage of this plugin described in the examples it is not necessary to deal with CuMatrix.
The setScaleContents method controls whether the image scales or not when the widget geometry changes (for example within a layout). If scale contents is false, then the image can be zoom and placed in a scroll area to improve its management (see QuImgScrollAreaI).
Error related methods
A custom image can be set in case of error (setErrorImage). The error condition can be triggered manually with setError or set internally by the cumbia engine, if it has been enabled through QuImagePluginInterface::init and QuImageBaseI::setSource has been called. The same logic applies to setErrorMessage.
Color tables
The setColorTable allows changing the image color table. colorTable returns the one in use.
Mouse events
Mouse events (press, release, move, wheel) can be intercepted by implementations of QuImageMouseEventIf. setImageMouseEventInterface installs the mouse event interface. When a mouse interface is installed, the QuImageBaseI shall not process mouse events automatically (for example, zooming).
Mapping image to widget geometry
mapToImg functions map a point (or a rectangle) from widget coordinates to image coordinates. mapFromImg map a point (or QRect) from image coordinates to widget coordinates.
Zoom
Zooming is enabled by default if scaleContents is false. Zoom can be disabled with setZoomEnabled and the level can be changed with setZoomLevel. The level shall be given as a percentage.
QuImageBaseI widget implementation
QuImageBase is implemented by QuImageWidget and QuImageGLWidget, that are QWidget derived objects. The asWidget method, returns a pointer to QuImageBase as QWidget. Qt properties and signal/slot connections can be exploited.
Connecting to cumbia
The setSource method connects the image to a cumbia source. The supported engines rely on cumbia and application level configurations. The source method returns the source of data in use. In order for connections to work, QuImagePluginInterface::init shall be called beforehand
Constructor & Destructor Documentation
~QuImageBaseI()
virtual QuImageBaseI::~QuImageBaseI () inline virtual
Member Function Documentation
asWidget()
virtual QWidget* QuImageBaseI::asWidget () const pure virtual
Implemented in QuImageGLWidget, and QuImageBase.
Referenced by CuImagePlugin::layout(), and QuImgScrollArea::setImage().
colorTable()
virtual QVector<QRgb>& QuImageBaseI::colorTable () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
error()
virtual bool QuImageBaseI::error () const pure virtual
Implemented in QuImageGLWidget, and QuImageBase.
errorImage()
virtual QImage QuImageBaseI::errorImage () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
image()
virtual QImage& QuImageBaseI::image () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
isOpenGL()
virtual bool QuImageBaseI::isOpenGL () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
mapFromImg() [1/2]
virtual QPoint QuImageBaseI::mapFromImg (const QPoint & p) const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
Referenced by QuImgScrollArea::onZoomRectChanged().
mapFromImg() [2/2]
virtual QRect QuImageBaseI::mapFromImg (const QRect & p) const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
mapToImg() [1/2]
virtual QPoint QuImageBaseI::mapToImg (const QPoint & p) const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
mapToImg() [2/2]
virtual QRect QuImageBaseI::mapToImg (const QRect & p) const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
scaleContents()
virtual bool QuImageBaseI::scaleContents () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
Referenced by QuImage::scaleContents().
setColorTable()
virtual void QuImageBaseI::setColorTable (const QVector< QRgb > & rgb) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
setError()
virtual void QuImageBaseI::setError (bool error) pure virtual
Implemented in QuImageGLWidget, and QuImageBase.
setErrorImage()
virtual void QuImageBaseI::setErrorImage (const QImage & i) pure virtual
Implemented in QuImageGLWidget, and QuImageBase.
setErrorMessage()
virtual void QuImageBaseI::setErrorMessage (const QString & msg) pure virtual
Implemented in QuImageGLWidget, and QuImageBase.
setImage() [1/4]
virtual void QuImageBaseI::setImage (const CuMatrix< double > & image) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
Referenced by QuImage::QuImage().
setImage() [2/4]
virtual void QuImageBaseI::setImage (const CuMatrix< unsigned char > & image) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
setImage() [3/4]
virtual void QuImageBaseI::setImage (const CuMatrix< unsigned short > & image) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
setImage() [4/4]
virtual void QuImageBaseI::setImage (const QImage & img) pure virtual
Implemented in QuImageBase, and QuImageGLWidget.
setImageMouseEventInterface()
virtual void QuImageBaseI::setImageMouseEventInterface (QuImageMouseEventIf * ifa) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
setScaleContents()
virtual void QuImageBaseI::setScaleContents (bool scale) pure virtual
Implemented in QuImageGLWidget, and QuImageBase.
Referenced by QuImgScrollArea::setScaleContents(), and QuImage::setScaleContents().
setSource()
virtual void QuImageBaseI::setSource (const QString & src) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
Referenced by QuImage::setSource().
setZoomEnabled()
virtual void QuImageBaseI::setZoomEnabled (bool en) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
setZoomLevel()
virtual void QuImageBaseI::setZoomLevel (float l) pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
source()
virtual QString QuImageBaseI::source () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
Referenced by QuImage::source().
unsetSource()
virtual void QuImageBaseI::unsetSource () pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
zoomEnabled()
virtual bool QuImageBaseI::zoomEnabled () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
zoomLevel()
virtual float QuImageBaseI::zoomLevel () const pure virtual
Implemented in QuImageWidget, QuImageGLWidget, and QuImageBase.
The documentation for this class was generated from the following file:
quimageplugininterface.h