cumbia-image plugin: QuImgScrollAreaI Class Reference
QuImgScrollAreaI Class Reference abstract
A QScrollArea dedicated to hosting a QuImageBaseI.
#include <quimageplugininterface.h>
Public Member Functions
virtual ~QuImgScrollAreaI ()
virtual QScrollArea * scrollArea ()=0
virtual void setImage (QuImageBaseI *ii)=0
virtual void setScaleContents (bool scale)=0
Detailed Description
You can get a new instance of QuImgScrollAreaI through QuImagePluginInterface::new_scroll_area, use setImage to set a QuImageBaseI on the scroll area and finally add the scroll area to a layout, either manually or through QuImagePluginInterface::layout(QuImgScrollAreaI scroll_a, QWidget container).
The scrollArea method returns this object as a QScrollArea. The setScaleContents called with a true parameter disables scrolling and scales the image according to the changes in the area geometry. Scroll bars can be used to move the image in the view otherwise. Remember that zooming is possible only if scale contents is false.
An example is provided in the introduction.
Constructor & Destructor Documentation
~QuImgScrollAreaI()
virtual QuImgScrollAreaI::~QuImgScrollAreaI () inline virtual
Member Function Documentation
scrollArea()
virtual QScrollArea* QuImgScrollAreaI::scrollArea () pure virtual
Implemented in QuImgScrollArea.
Referenced by CuImagePlugin::layout(), and QuImage::QuImage().
setImage()
virtual void QuImgScrollAreaI::setImage (QuImageBaseI * ii) pure virtual
Implemented in QuImgScrollArea.
Referenced by QuImage::QuImage().
setScaleContents()
virtual void QuImgScrollAreaI::setScaleContents (bool scale) pure virtual
The documentation for this class was generated from the following file:
quimageplugininterface.h