cumbia-image plugin: QuImageGLWidget Class Reference
QuImageGLWidget Class Reference
#include <quimageGLwidget.h>
Public Member Functions
QuImageGLWidget (QWidget *parent, CumbiaPool *cu_p, const CuControlsFactoryPool &fpoo)
virtual ~QuImageGLWidget ()
void setImage (const QImage &image)
bool scaleContents () const
void setScaleContents (bool scale)
QImage & image () const
void setErrorImage (const QImage &i)
QImage errorImage () const
bool error () const
void setError (bool error)
void setErrorMessage (const QString &msg)
void setColorTable (const QVector< QRgb > &rgb)
QVector< QRgb > & colorTable () const
void setImageMouseEventInterface (QuImageMouseEventIf *ifa)
bool isOpenGL () const
bool zoomEnabled () const
void setZoomLevel (float n)
void setZoomEnabled (bool en)
float zoomLevel () const
QWidget * asWidget () const
void setImage (const CuMatrix< double > &image)
void setImage (const CuMatrix< unsigned short > &image)
void setImage (const CuMatrix< unsigned char > &image)
QString source () const
void setSource (const QString &src)
void unsetSource ()
virtual QPoint mapToImg (const QPoint &p) const
virtual QRect mapToImg (const QRect &r) const
virtual QPoint mapFromImg (const QPoint &p) const
virtual QRect mapFromImg (const QRect &r) const
Public Member Functions inherited from QuImageBaseI
virtual ~QuImageBaseI ()
Protected Member Functions
void paintEvent (QPaintEvent *)
void mousePressEvent (QMouseEvent *ev)
void mouseMoveEvent (QMouseEvent *ev)
void mouseReleaseEvent (QMouseEvent *ev)
Constructor & Destructor Documentation
QuImageGLWidget()
QuImageGLWidget::QuImageGLWidget (QWidget * parent, CumbiaPool * cu_p, const CuControlsFactoryPool & fpoo) explicit
~QuImageGLWidget()
QuImageGLWidget::~QuImageGLWidget () virtual
References QuImageGLWidgetPrivate::imgb.
Member Function Documentation
asWidget()
QWidget * QuImageGLWidget::asWidget () const virtual
Implements QuImageBaseI.
References QuImageBase::asWidget(), and QuImageGLWidgetPrivate::imgb.
colorTable()
QVector< QRgb > & QuImageGLWidget::colorTable () const virtual
Implements QuImageBaseI.
References QuImageBase::colorTable(), and QuImageGLWidgetPrivate::imgb.
error()
bool QuImageGLWidget::error () const virtual
Implements QuImageBaseI.
References QuImageBase::error(), and QuImageGLWidgetPrivate::imgb.
Referenced by setError().
errorImage()
QImage QuImageGLWidget::errorImage () const virtual
Implements QuImageBaseI.
References QuImageBase::errorImage(), and QuImageGLWidgetPrivate::imgb.
image()
QImage & QuImageGLWidget::image () const virtual
Implements QuImageBaseI.
References QuImageBase::image(), and QuImageGLWidgetPrivate::imgb.
Referenced by setImage().
isOpenGL()
bool QuImageGLWidget::isOpenGL () const virtual
Implements QuImageBaseI.
mapFromImg() [1/2]
QPoint QuImageGLWidget::mapFromImg (const QPoint & p) const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::mapFromImg().
mapFromImg() [2/2]
QRect QuImageGLWidget::mapFromImg (const QRect & r) const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::mapFromImg().
mapToImg() [1/2]
QPoint QuImageGLWidget::mapToImg (const QPoint & p) const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::mapToImg().
mapToImg() [2/2]
QRect QuImageGLWidget::mapToImg (const QRect & r) const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::mapToImg().
mouseMoveEvent()
void QuImageGLWidget::mouseMoveEvent (QMouseEvent * ev) protected
References QuImageGLWidgetPrivate::imgb, and QuImageBase::mouseMove().
mousePressEvent()
void QuImageGLWidget::mousePressEvent (QMouseEvent * ev) protected
References QuImageGLWidgetPrivate::imgb, and QuImageBase::mousePress().
mouseReleaseEvent()
void QuImageGLWidget::mouseReleaseEvent (QMouseEvent * ev) protected
References QuImageGLWidgetPrivate::imgb, and QuImageBase::mouseRelease().
paintEvent()
void QuImageGLWidget::paintEvent (QPaintEvent * e) protected
References QuImageGLWidgetPrivate::imgb, and QuImageBase::paint().
scaleContents()
bool QuImageGLWidget::scaleContents () const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::scaleContents().
setColorTable()
void QuImageGLWidget::setColorTable (const QVector< QRgb > & rgb) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setColorTable().
setError()
void QuImageGLWidget::setError (bool error) virtual
Implements QuImageBaseI.
References error(), QuImageGLWidgetPrivate::imgb, and QuImageBase::setError().
setErrorImage()
void QuImageGLWidget::setErrorImage (const QImage & i) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setErrorImage().
setErrorMessage()
void QuImageGLWidget::setErrorMessage (const QString & msg) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setErrorMessage().
setImage() [1/4]
void QuImageGLWidget::setImage (const CuMatrix< double > & image) virtual
Implements QuImageBaseI.
References image(), QuImageGLWidgetPrivate::imgb, and QuImageBase::setImage().
setImage() [2/4]
void QuImageGLWidget::setImage (const CuMatrix< unsigned char > & image) virtual
Implements QuImageBaseI.
References image(), QuImageGLWidgetPrivate::imgb, and QuImageBase::setImage().
setImage() [3/4]
void QuImageGLWidget::setImage (const CuMatrix< unsigned short > & image) virtual
Implements QuImageBaseI.
References image(), QuImageGLWidgetPrivate::imgb, and QuImageBase::setImage().
setImage() [4/4]
void QuImageGLWidget::setImage (const QImage & image) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setImage().
setImageMouseEventInterface()
void QuImageGLWidget::setImageMouseEventInterface (QuImageMouseEventIf * ifa) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setImageMouseEventInterface().
setScaleContents()
void QuImageGLWidget::setScaleContents (bool scale) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setScaleContents().
setSource()
void QuImageGLWidget::setSource (const QString & src) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setSource().
setZoomEnabled()
void QuImageGLWidget::setZoomEnabled (bool en) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setZoomEnabled().
setZoomLevel()
void QuImageGLWidget::setZoomLevel (float n) virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::setZoomLevel().
source()
QString QuImageGLWidget::source () const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::source().
unsetSource()
void QuImageGLWidget::unsetSource () virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::unsetSource().
zoomEnabled()
bool QuImageGLWidget::zoomEnabled () const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::zoomEnabled().
zoomLevel()
float QuImageGLWidget::zoomLevel () const virtual
Implements QuImageBaseI.
References QuImageGLWidgetPrivate::imgb, and QuImageBase::zoomLevel().
The documentation for this class was generated from the following files:
quimageGLwidget.h
quimageGLwidget.cpp