cumbia-image plugin: QuImageMouseEventIf Class Reference
QuImageMouseEventIf Class Reference abstract
#include <quimagemouseeventif.h>
Public Member Functions
QuImageMouseEventIf ()
virtual void imageMousePressEvent (const QPoint &pos, int button)=0
virtual void imageMouseReleaseEvent (const QPoint &pos, int button)=0
virtual void imageMouseMoveEvent (const QPoint &pos, int button)=0
virtual void imageMouseWheelEvent (QWheelEvent *event)=0
Constructor & Destructor Documentation
QuImageMouseEventIf()
QuImageMouseEventIf::QuImageMouseEventIf ()
Member Function Documentation
imageMouseMoveEvent()
virtual void QuImageMouseEventIf::imageMouseMoveEvent (const QPoint & pos, int button) pure virtual
Referenced by QuImgMouseTracker::mouseMove().
imageMousePressEvent()
virtual void QuImageMouseEventIf::imageMousePressEvent (const QPoint & pos, int button) pure virtual
Referenced by QuImgMouseTracker::mousePress().
imageMouseReleaseEvent()
virtual void QuImageMouseEventIf::imageMouseReleaseEvent (const QPoint & pos, int button) pure virtual
Referenced by QuImgMouseTracker::mouseRelease().
imageMouseWheelEvent()
virtual void QuImageMouseEventIf::imageMouseWheelEvent (QWheelEvent * event) pure virtual
Referenced by QuImgMouseTracker::wheelEvent().
The documentation for this class was generated from the following file:
quimagemouseeventif.h