cumbia-image plugin: QuImage Class Reference
QuImage Class Reference
#include <quimage.h>
Public Slots
void setSource (QString source)
void setScaleContents (bool scaleContents)
Public Member Functions
QuImage (QWidget *parent)
QuImage (QWidget *parent, CumbiaPool *cu_p, const CuControlsFactoryPool &fpoo)
~QuImage ()
QString source () const
bool scaleContents () const
Properties
QString source
bool scaleContents
Constructor & Destructor Documentation
QuImage() [1/2]
QuImage::QuImage (QWidget * parent) inline
References QuImagePrivate::ii, and QuImagePrivate::scaleContents.
QuImage() [2/2]
QuImage::QuImage (QWidget * parent, CumbiaPool * cu_p, const CuControlsFactoryPool & fpoo) inline
References QuImagePluginInterface::file_name(), QuImagePluginInterface::get_instance(), QuImagePrivate::ii, QuImagePluginInterface::init(), QuImagePluginInterface::new_image(), QuImagePluginInterface::new_scroll_area(), QuImagePrivate::scaleContents, QuImgScrollAreaI::scrollArea(), QuImageBaseI::setImage(), and QuImgScrollAreaI::setImage().
~QuImage()
QuImage::~QuImage () inline
Member Function Documentation
scaleContents()
bool QuImage::scaleContents () const inline
References QuImagePrivate::ii, and QuImageBaseI::scaleContents().
setScaleContents
void QuImage::setScaleContents (bool scaleContents) inline slot
References QuImagePrivate::ii, scaleContents, and QuImageBaseI::setScaleContents().
setSource
void QuImage::setSource (QString source) inline slot
References QuImagePrivate::ii, QuImageBaseI::setSource(), and source.
source()
QString QuImage::source () const inline
References QuImagePrivate::ii, and QuImageBaseI::source().
Property Documentation
scaleContents
bool QuImage::scaleContents read write
Referenced by setScaleContents().
source
QString QuImage::source read write
Referenced by setSource().
The documentation for this class was generated from the following file:
quimage.h